"""empty message

Revision ID: ba09afaae4cb
Revises: 
Create Date: 2020-05-18 10:42:41.648872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba09afaae4cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.drop_column('movies', 'releaseDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('releaseDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_date')
    # ### end Alembic commands ###
